#! /bin/bash
selectors="lex nsga2 hype"
#variators="dtlz2 knapsack zdt6"
variators="dtlz1_m3 dtlz2_m3 dtlz3_m3 dtlz4_m3 dtlz1_m5 dtlz1_m25 dtlz1_m50 dtlz1_m75 dtlz1_m100 dtlz2_m5 dtlz2_m25 dtlz2_m50 dtlz2_m75 dtlz2_m100 dtlz3_m5 dtlz3_m25 dtlz3_m50 dtlz3_m75 dtlz3_m100 dtlz4_m5 dtlz4_m25 dtlz4_m50 dtlz4_m75 dtlz4_m100"

for sel in $selectors ; do
    for var in $variators ; do
        #for t in {1..30} ; do
            # copy PISA_cfg to specific config file
            echo "cp "$var"_linux/PISA_cfg "$var"_linux/"$sel"_"$var"_cfg"
            cp "$var"_linux/PISA_cfg "$var"_linux/"$sel"_"$var"_cfg
            if [ $sel = epsmoea ] ; then
                # replace mu = blah with mu = 2
                sed -i -e "s/mu.*/mu 2/g" "$var"_linux/"$sel"_"$var"_cfg
            fi
       # done ;
    done ; 
done ;
