#!/bin/bash

selectors="lex"
#variators="dtlz2 knapsack zdt6"
variators="dtlz1_m25 dtlz1_m50 dtlz1_m75 dtlz1_m100 dtlz2_m25 dtlz2_m50 dtlz2_m75 dtlz2_m100 dtlz3_m25 dtlz3_m50 dtlz3_m75 dtlz3_m100 dtlz4_m25 dtlz4_m50 dtlz4_m75 dtlz4_m100"

for var in $variators ; do
    rm "$var"_linux/PISA_ini    
    rm "$var"_linux/PISA_sta
    rm "$var"_linux/PISA_sel
    rm "$var"_linux/PISA_arc
    rm "$var"_linux/PISA_var
done
